title = "Custom Gitleaks Rules"

[[rules]]
id = "terraform-admin-password"

description = "Hardcoded Terraform admin password"

regex = '''(?i)admin_password\s*=\s*"[^"]+"'''

secretGroup = 0

tags = ["terraform", "password"]
